backend/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, skip: :sessions,
    controllers: {sessions: "admins/sessions", passwords: "admins/passwords"}

  scope module: "admins", path: "admins", as: :admins do
    devise_scope :admin do
      get "login", to: "sessions#new"
      get "logout", to: "sessions#destroy"
      post "sign_in", to: "sessions#create", as: :sessions
    end
    get "/dashboard", to: "dashboards#index"
    resources :admin_profiles, as: :profile, only: [:show, :update]
    resources :products
    resources :roles
    resources :providers
    resources :catalogs
    resources :abouts
    resources :categories, except: [:show, :new, :edit]
    resources :branches
  end

  # scope module: "homes" do
  #   root "homepages#index"
  #   get ":product_type_id/:id", to: "products#show", as: "product"
  # end

  # scope module: "users" do
  #   devise_scope :user do
  #     get "dang-nhap", to: "sessions#new", as: "login"
  #     get "dang-xuat", to: "sessions#destroy", as: "logout"
  #     get "dang-ky", to: "registrations#new", as: "register"
  #     get "quen-mat-khau", to: "passwords#new", as: "forgot_password"
  #   end
  #   get "trang-ca-nhan", to: "dashboards#index", as: "dashboard"
  #   get "thay-doi-thong-tin", to: "profiles#show", as: "show_profile"
  #   put "thay-doi-thong-tin", to: "profiles#update", as: "update_profile"
  #   get "tao-moi-tin-rao", to: "products#new", as: "new_product"
  #   get "quan-ly-tin-rao", to: "products#index", as: "products"
  #   resources :products do
  #     collection do
  #       get "load_data"
  #     end
  #   end
  #   resources :provinces
  # end
end

backend/app/models/about.rb
class About < ApplicationRecord
  belongs_to :admin
end

backend/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :branches
  has_many :abouts
  has_many :products
  has_many :articles
  belongs_to :role

end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :category
end

backend/app/models/branch.rb
class Branch < ApplicationRecord
  has_many :branch_images
end

backend/app/models/branch_image.rb
class BranchImage < ApplicationRecord
  belongs_to :branch
end

backend/app/models/catalog.rb
class Catalog < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def normalize_friendly_id(input)
    ConvertEnNameService.normalize_with_hyphen(input).downcase
  end

  has_many :provider_details
  has_many :providers, through: :provider_details

  before_create :conver_title

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  def conver_title
    ConvertEnNameService.normalize_with_hyphen(self.name)
  end
end

backend/app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :articles

  validates :name, presence: true

  def should_generate_new_friendly_id?
    name_changed?
  end
end

backend/app/models/contact.rb
class Contact < ApplicationRecord
end

backend/app/models/image_slider.rb
class ImageSlider < ApplicationRecord
end

backend/app/models/paint.rb
class Paint < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def normalize_friendly_id(input)
    ConvertEnNameService.normalize_with_hyphen(input).downcase
  end

  has_many :provider_details
  has_many :providers, through: :provider_details
  has_many :paints

  before_create :conver_title

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  def conver_title
    ConvertEnNameService.normalize_with_hyphen(self.name)
  end
end

backend/app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  has_many :product_images

  belongs_to :admin
  belongs_to :provider
  belongs_to :paint

  has_one :product_detail
end

backend/app/models/product_detail.rb
class ProductDetail < ApplicationRecord

  has_one :product
end

backend/app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
end

backend/app/models/provider.rb
class Provider < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def normalize_friendly_id(input)
    ConvertEnNameService.normalize_with_hyphen(input).downcase
  end

  has_many :provider_details
  has_many :paints, through: :provider_details
  has_many :products
  has_many :quotations

  before_create :conver_title

  validates :name, presence: true,
    length: {
      maximum: Settings.provider.name.max_length,
    }

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  def conver_title
    ConvertEnNameService.normalize_with_hyphen(self.name)
  end
end

backend/app/models/provider_detail.rb
class ProviderDetail < ApplicationRecord
  belongs_to :provider
  belongs_to :paint
end

backend/app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :provider
end

backend/app/models/role.rb
class Role < ApplicationRecord
  has_many :admins
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "authenticate"
    end
  end

  def set_locale
    I18n.locale = :vi
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
  def ng_pagination total_items, current_page, items_per_page, event_handler
    "<ul uib-pagination
      ng-if=#{total_items}
      total-items=#{total_items}
      ng-model=#{current_page}
      max-size='5'
      items-per-page=#{items_per_page}
      class='pagination-sm'
      boundary-links='true'
      rotate='false'
      ng-change=#{event_handler}
      first-text='<<'
      last-text='>>'
      next-text='>'
      previous-text='<'
      >
    </ul>".html_safe
  end
end

backend/app/views/layouts/admin_manager.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bách hóa sơn</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin_manager', media: 'all' %>
    <%= javascript_include_tag 'admin_manager' %>
  </head>
  <body ng-app="adminApp" ng-strict-di>
    <div class="preloader themed-background">
      <h1 class="push-top-bottom text-light text-center"><strong>Pro</strong>UI</h1>
      <div class="inner">
        <h3 class="text-light visible-lt-ie9 visible-lt-ie10"><strong>Loading..</strong></h3>
        <div class="preloader-spinner hidden-lt-ie9 hidden-lt-ie10"></div>
      </div>
    </div>
    <div id="page-container" class="sidebar-partial sidebar-visible-lg sidebar-no-animations">
      <%= render "layouts/admins/sidebar_alt" %>
      <%= render "layouts/admins/sidebar" %>
      <div id="main-container">
        <%= render "layouts/admins/header" %>
        <%= yield %>
        <%= render "layouts/admins/footer" %>
      </div>
      <a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>
      <%= render "layouts/admins/user_setting_modal" %>
    </div>
    <%= javascript_include_tag 'ng_admin' %>
  </body>
</html>

backend/app/views/layouts/admins/_footer.html.erb
<footer class="clearfix">
  <div class="pull-right">
    Development <i class="fa fa-heart text-danger"></i> by <a href="#" target="_blank">NEETs Team</a>
  </div>
  <div class="pull-left">
    <span>2018</span> &copy; <a href="#" target="_blank">Realty Project</a>
  </div>
</footer>

backend/app/views/layouts/admins/_header.html.erb
<header class="navbar navbar-default">
  <ul class="nav navbar-nav-custom">
    <li>
      <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');">
      <i class="fa fa-bars fa-fw"></i>
      </a>
    </li>
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
      <i class="gi gi-settings"></i>
      </a>
      <ul class="dropdown-menu dropdown-custom dropdown-options">
        <li class="dropdown-header text-center">Header Style</li>
        <li>
          <div class="btn-group btn-group-justified btn-group-sm">
            <a href="javascript:void(0)" class="btn btn-primary" id="options-header-default">Light</a>
            <a href="javascript:void(0)" class="btn btn-primary" id="options-header-inverse">Dark</a>
          </div>
        </li>
        <li class="dropdown-header text-center">Page Style</li>
        <li>
          <div class="btn-group btn-group-justified btn-group-sm">
            <a href="javascript:void(0)" class="btn btn-primary" id="options-main-style">Default</a>
            <a href="javascript:void(0)" class="btn btn-primary" id="options-main-style-alt">Alternative</a>
          </div>
        </li>
        <li class="dropdown-header text-center">Main Layout</li>
        <li>
          <button class="btn btn-sm btn-block btn-primary" id="options-header-top">Fixed Side/Header (Top)</button>
          <button class="btn btn-sm btn-block btn-primary" id="options-header-bottom">Fixed Side/Header (Bottom)</button>
        </li>
        <li class="dropdown-header text-center">Footer</li>
        <li>
          <div class="btn-group btn-group-justified btn-group-sm">
            <a href="javascript:void(0)" class="btn btn-primary" id="options-footer-static">Default</a>
            <a href="javascript:void(0)" class="btn btn-primary" id="options-footer-fixed">Fixed</a>
          </div>
        </li>
      </ul>
    </li>
  </ul>
  <!-- Search Form -->
  <form action="page_ready_search_results.html" method="post" class="navbar-form-custom" role="search">
    <div class="form-group">
      <input type="text" id="top-search" name="top-search" class="form-control" placeholder="Search..">
    </div>
  </form>
  <ul class="nav navbar-nav-custom pull-right">
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
      <%= image_tag "avatar-default.png" %> <i class="fa fa-angle-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
        <li class="dropdown-header text-center">Account</li>
        <li class="divider"></li>
        <li>
          <a href="page_ready_user_profile.html">
          <i class="fa fa-user fa-fw pull-right"></i>
          Profile
          </a>
          <a href="#modal-user-settings" data-toggle="modal">
          <i class="fa fa-cog fa-fw pull-right"></i>
          Settings
          </a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="page_ready_lock_screen.html"><i class="fa fa-lock fa-fw pull-right"></i> Lock Account</a>
          <a href="<%= admins_logout_path %>"><i class="fa fa-ban fa-fw pull-right"></i> Logout</a>
        </li>
      </ul>
    </li>
  </ul>
</header>

backend/app/views/layouts/admins/_sidebar.html.erb
<div id="sidebar">
  <div class="sidebar-scroll">
    <div class="sidebar-content">
      <%= link_to admins_dashboard_path, class: "sidebar-brand" do %>
        <strong>NEETs</strong>Team
      <% end %>
      <div class="sidebar-section sidebar-user clearfix">
        <div class="sidebar-user-avatar">
          <a href="page_ready_user_profile.html">
          <%= image_tag "avatar-default.png" %>
          </a>
        </div>
        <div class="sidebar-user-name"><%= current_admin.name %></div>
        <div class="sidebar-user-links">
          <a href="<%= admins_profile_path current_admin %>"
            data-toggle="tooltip" data-placement="bottom" title="Profile">
               <i class="gi gi-user"></i>
          </a>
          <a href="page_ready_inbox.html" data-toggle="tooltip" data-placement="bottom" title="Messages"><i class="gi gi-envelope"></i></a>
          <a href="#modal-user-settings" data-toggle="modal" class="enable-tooltip" data-placement="bottom" title="Settings"><i class="gi gi-cogwheel"></i></a>
          <a href="login.html" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="gi gi-exit"></i></a>
        </div>
      </div>
      <ul class="sidebar-nav">
        <li>
          <a href="dashboard" class=" active"><i class="gi gi-stopwatch sidebar-nav-icon"></i>Bảng điều khiển</a>
        </li>
        <li class="sidebar-header">
          <span class="sidebar-header-options clearfix"><a href="javascript:void(0)" data-toggle="tooltip" title="Quick Settings"><i class="gi gi-settings"></i></a></span>
          <span class="sidebar-header-title">Quản trị tài nguyên</span>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-parents sidebar-nav-icon"></i>Vai trò trên trang</a>
          <ul>
            <li>
              <a href="#">List</a>
            </li>
            <li>
              <a href="#">Add</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-user sidebar-nav-icon"></i>Quản trị viên</a>
          <ul>
            <li>
              <a href="#">List</a>
            </li>
            <li>
              <a href="#">Add</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-shop sidebar-nav-icon"></i>Chuỗi đại lý</a>
          <ul>
            <li>
              <a href="#">List</a>
            </li>
            <li>
              <a href="#">Add</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-globe_af sidebar-nav-icon"></i>Nhà cung cấp</a>
          <ul>
            <li>
              <%= link_to "Quản lý nhà cung cấp", admins_providers_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-justify sidebar-nav-icon"></i>Danh mục sản phẩm</a>
          <ul>
            <li>
              <%= link_to "Danh mục sơn && bột trét", admins_catalogs_path %>
            </li>
            <li>
              <%= link_to "Tạo mới danh mục", new_admins_catalog_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-tint sidebar-nav-icon"></i>Sản phẩm</a>
          <ul>
            <li>
              <a href="#">List</a>
            </li>
            <li>
              <%= link_to "Tạo mới sản phẩm", new_admins_product_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-justify sidebar-nav-icon"></i>Danh mục tin tức</a>
          <ul>
            <li>
              <%= link_to "Quản lý danh mục tin", admins_categories_path %>
            </li>
            <li>
              <a href="#">Add</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-pencil sidebar-nav-icon"></i>Tin tức</a>
          <ul>
            <li>
              <a href="#">List</a>
            </li>
            <li>
              <a href="#">Add</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-coins sidebar-nav-icon"></i>Báo giá hãng</a>
          <ul>
            <li>
              <a href="#">List</a>
            </li>
            <li>
              <a href="#">Add</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="gi gi-picture sidebar-nav-icon"></i>Slider quảng cáo</a>
          <ul>
            <li>
              <a href="#">List</a>
            </li>
            <li>
              <a href="#">Add</a>
            </li>
          </ul>
        </li>

        <li class="sidebar-header">
          <span class="sidebar-header-options clearfix"><a href="javascript:void(0)" data-toggle="tooltip" title="Quick Settings"><i class="gi gi-circle_info"></i></a></span>
          <span class="sidebar-header-title">Giới thiệu công ty</span>
        </li>
        <li>
          <a href="subscribles"><i class="gi gi-circle_question_mark sidebar-nav-icon"></i>Thông tin công ty</a>
        </li>

        <li class="sidebar-header">
          <span class="sidebar-header-options clearfix"><a href="javascript:void(0)" data-toggle="tooltip" title="Quick Settings"><i class="gi gi-settings"></i></a></span>
          <span class="sidebar-header-title">Chăm sóc khách hàng</span>
        </li>
        <li>
          <a href="subscribles"><i class="fa fa-envelope-o sidebar-nav-icon"></i>Thư liên hệ</a>
        </li>
      </ul>
    </div>
  </div>
</div>

backend/app/views/layouts/admins/_sidebar_alt.html.erb
<div id="sidebar-alt">
  <div class="sidebar-scroll">
    <div class="sidebar-content">
    </div>
  </div>
</div>

backend/app/views/layouts/admins/_user_setting_modal.html.erb
<div id="modal-user-settings" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h2 class="modal-title"><i class="fa fa-pencil"></i> Settings</h2>
      </div>
      <div class="modal-body">
        <form action="index.html" method="post" enctype="multipart/form-data" class="form-horizontal form-bordered" onsubmit="return false;">
          <fieldset>
            <legend>Vital Info</legend>
            <div class="form-group">
              <label class="col-md-4 control-label">Username</label>
              <div class="col-md-8">
                <p class="form-control-static">Admin</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-email">Email</label>
              <div class="col-md-8">
                <input type="email" id="user-settings-email" name="user-settings-email" class="form-control" value="admin@example.com">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-notifications">Email Notifications</label>
              <div class="col-md-8">
                <label class="switch switch-primary">
                <input type="checkbox" id="user-settings-notifications" name="user-settings-notifications" value="1" checked>
                <span></span>
                </label>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <legend>Password Update</legend>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-password">New Password</label>
              <div class="col-md-8">
                <input type="password" id="user-settings-password" name="user-settings-password" class="form-control" placeholder="Please choose a complex one..">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-repassword">Confirm New Password</label>
              <div class="col-md-8">
                <input type="password" id="user-settings-repassword" name="user-settings-repassword" class="form-control" placeholder="..and confirm it!">
              </div>
            </div>
          </fieldset>
          <div class="form-group form-actions">
            <div class="col-xs-12 text-right">
              <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-sm btn-primary">Save Changes</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bds</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/layouts/authenticate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecoinomic</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'authenticate', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'authenticate', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>